ARG ROS_DISTRO=noetic
FROM osrf/ros:$ROS_DISTRO-desktop-full

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y \
    apt-utils \
    ros-$ROS_DISTRO-tf2-sensor-msgs \
    ros-$ROS_DISTRO-tf2-geometry-msgs \
    ros-$ROS_DISTRO-mavros* \
    ros-$ROS_DISTRO-vision-opencv \
    ros-$ROS_DISTRO-image-transport \
    ros-$ROS_DISTRO-depth-image-proc \
    libyaml-cpp-dev \
    python3-pip python3-yaml python3-setuptools && \
    pip3 install rospkg catkin-pkg catkin-tools && \
    echo 'source /opt/ros/$ROS_DISTRO/setup.bash' >> ~/.bashrc && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean